exceptionless/Exceptionless.Net

Source/Platforms/Mvc/NuGet/tools/uninstall.ps1, Source/Platforms/Web/NuGet/tools/uninstall.ps1, Source/Platforms/WebApi/NuGet/tools/uninstall.ps1, Source/Shared/NuGet/tools/exceptionless.psm1
Pass the platform from uninstall.ps1 to remove_config function, and use
the same rules to delete the ExceptionlessModule from
system.web/httpModules and system.webServer/modules as were used to
insert
=> Fix for issue #27 (nuget update of WebApi removes Exceptionless module)

Source/Extras/Extensions/ExceptionlessExtraConfigurationExtensions.cs, Source/Shared/Configuration/ExceptionlessAttribute.cs, Source/Shared/Configuration/ExceptionlessConfiguration.cs
I noticed there was a race condition that may be reintroduced here https://github.com/exceptionless/Exceptionless.Net/commit/da1f9f3ff00ea0fe8076d27d6a519811e2cf4ba0. However, I now think it's caused by the http modules calling startup multiple times and an exception happening.
@ejsmith :
1. Should we add checks to the modules to ensure init only happens once?
2. The environmental variable names are consistent with the app settings variables... Do you like this name?
3. Do you think we should drop enable ssl? To me it should be determined if you have https or http defined as part of the server url and we shouldn't be changing the url..
=> Pull request for  #37 Added the ability to read settings from environmental variables.

Source/Samples/SampleMvc/Exceptionless.SampleMvc.csproj, Source/Samples/SampleMvc/Web.config, Source/Shared/Extensions/ExceptionlessConfigurationExtensions.cs
The scheme would be set to 443 always when it shouldn't of been set.
This code is now driven off of the scheme specified. @ejsmith  I don't
even think we need this code block anymore because the underlying uri
parser looks to be setting the port correctly based on the scheme.
=> Fixed an issue with self hosted installs that used AppSettings.

Source/Tests/Exceptionless.Tests.csproj
When I first cloned the repository, the Exceptionless.Tests did not compile due to a missing reference to System.Runtime
=> add missing Reference Include

Source/Platforms/Wpf/Dialogs/CrashReportDialog.xaml, Source/Platforms/Wpf/ExceptionlessClientExtensions.cs
@niemyjski here is a pull request for my first problem described in #60.
Buttons now use padding instead of hardcoded width. I have also added margins to achieve better spacing between controls. 
I have also included a minor fix to log messages.
=> Fix CrashReportDialog styling

Source/Platforms/WebApi/ExceptionlessHandleErrorAttribute.cs, Source/Platforms/WebApi/ExceptionlessWebApiExtensions.cs
This ensures that exceptions handled by the WebApi `ExceptionlessHandleErrorAttribute` are processed by the same `ExceptionlessClient` that was passed to `RegisterWebApi`. Prior to this, `ExceptionlessHandleErrorAttribute` would always use `ExceptionlessClient.Default`, regardless of what was passed to `RegisterWebApi`.
=> Pass same ExceptionlessClient to WebApi exception filter

Source/Shared/EventBuilder.cs
This fixes the geolocation for cultures like the Dutch culture that
separate decimals with a comma instead of a point.
=> Fix geolocation for cultures that have a different separator for decimals

appveyor.yml
- Add some more AppVeyor information to the AV log output.
- For PR's, the build number doesn't increment. This helps (big time) when pushing up stuff up to nuget and having the PR not incremement build numbers.
=> 2x tweaks to the AppVeyor deployment script.

src/Exceptionless/Extensions/EventExtensions.cs, src/Exceptionless/Extensions/ExceptionlessClientExtensions.cs, src/Platforms/Exceptionless.AspNetCore/ExceptionlessAspNetCorePlugin.cs, src/Platforms/Exceptionless.AspNetCore/ExceptionlessExtensions.cs, src/Platforms/Exceptionless.Mvc/ExceptionlessModule.cs, src/Platforms/Exceptionless.Nancy/ExceptionlessNancyPlugin.cs, src/Platforms/Exceptionless.Web/ExceptionlessClientExtensions.cs, src/Platforms/Exceptionless.Web/ExceptionlessModule.cs, src/Platforms/Exceptionless.Web/ExceptionlessWebPlugin.cs, src/Platforms/Exceptionless.WebApi/ExceptionlessWebApiPlugin.cs
I went back and forth on whether I should add a new plugin just
to check this at the end of the pipeline but decided against adding
extra work at the cost of being non dry...
I also considered looking at all integration points to where we log
exceptions and do the 404 logic there, but that would also add a bunch
of duplicated logic (for wrapping http context, getting request info for
the source etc...) Also you might still want to log the exception object
that created the 404...
=> Fixed a bug where exceptions converted into 404's were not being run through exclusions

src/Exceptionless/Queue/DefaultEventQueue.cs
ExceptionlessClient.Default.ProcessQueue() wouldn't block when Processing is under way.
The fix changes DefaultEventQueue.Process() by introducing an instance of Task while Process() is running (instead of **bool _processingQueue**).
If Process() method is running it'd return its Task when further calls are made. So the caller can await its completition.
Also removes unnecessary call to processingQueue within OnProcessQueue method.
This PR fixes issue #147.
=> Fixes ProcessQueue method so it blocks until queue has been processed

src/Exceptionless/Logging/FileExceptionlessLog.cs
The projects that we are using exceptionless client sdk with, have been developed and deployed in Simplified Chinese Windows environment. When there are some system errors occurred, the content in exceptionless.log file will be messy. So the encoding of logging writer should be changed to Encoding.UTF8 to compatible the variety cultures.
=> Fix issue that the logging content cannot be recognized in Chinese environment.

src/Exceptionless/Storage/FolderObjectStorage.cs
Replace GetFiles with EnumerateFiles method to improve peformance of FolderObjectStorage while retrieving object list. Especially in the high throughput scenarios, there will be more than thousands files, the performance of GetFiles will be very bad. So replace with EnumerateFiles can be very fast to retrieve file name with limit. Please refer to [https://stackoverflow.com/questions/5669617/what-is-the-difference-between-directory-enumeratefiles-vs-directory-getfiles](https://stackoverflow.com/questions/5669617/what-is-the-difference-between-directory-enumeratefiles-vs-directory-getfiles)
=> Replace GetFiles with EnumerateFiles method to improve peformance in FolderObjectStorage

src/Exceptionless/Logging/FileExceptionlessLog.cs, test/Exceptionless.Tests/Log/FileExceptionlessLogTestBase.cs
The original file logger cannot record event time and level. It's hard to know when the error occurs, and which one is warn or error.
=> Add event time and level for the file logger.

src/Exceptionless/Plugins/Default/1010_DuplicateCheckerPlugin.cs
Fixes issue #182. 
I've fixed without changing the underlying data structures. Instead I just ensure the lock is released when resubmitting the MergedEvent. This ensures we can't cause a deadlock by some unknown code running from the ExceptionlessClient callbacks (SubmittingEvent). 
- There are no tests as it's not worth it for a deadlock.
- I tried to sign your CLA but got "We're sorry, but something went wrong."
=> Release lock before calling unknown code.

src/Exceptionless/Configuration/CertificateData.cs, src/Exceptionless/Configuration/ExceptionlessConfiguration.cs, src/Exceptionless/Extensions/ExceptionlessConfigurationExtensions.cs, src/Exceptionless/Newtonsoft.Json/Serialization/DefaultContractResolver.cs, src/Exceptionless/Submission/DefaultSubmissionClient.cs, test/Exceptionless.Tests/Configuration/CertificateValidationTest.cs
=> Server certificate validation

src/Exceptionless/ExceptionlessClient.cs, src/Exceptionless/Queue/DefaultEventQueue.cs, src/Exceptionless/Submission/DefaultSubmissionClient.cs, src/Exceptionless/Submission/SubmissionResponse.cs
Recently we have encountered an error which cannot be identified. Since the logging information is not enough.
The changes is to record much more details of the error while submitting events.
=> Recording exception details in logs to identify issues easier.

src/Exceptionless/Extensions/ExceptionlessConfigurationExtensions.cs
=> fix Startup failed while Assembly.GetCallingAssembly not supported

samples/Exceptionless.SampleAspNetCore/Startup.cs, src/Platforms/Exceptionless.Extensions.Logging/Exceptionless.Extensions.Logging.csproj, src/Platforms/Exceptionless.Extensions.Logging/ExceptionlessLoggerExtensions.cs
- Add ILoggingBuilder extension methods
- Markup ILoggerFactory extension methods obsolute
- Add sample codes in SampleAspNetCore
=> Add ILoggingBuilder extension methods

src/Exceptionless/Submission/SubmissionResponse.cs
Inspecting with [ObjectLayoutInspector](https://www.nuget.org/packages/ObjectLayoutInspector/) `TypeLayout.PrintLayout<SubmissionResponse>()`
Pre
```
Type layout for 'SubmissionResponse'
Size: 32 bytes. Paddings: 5 bytes (%15 of empty space)
|================================================================|
| Object Header (8 bytes)                                        |
|----------------------------------------------------------------|
| Method Table Ptr (8 bytes)                                     |
|================================================================|
|   0-7: String <Message>k__BackingField (8 bytes)               |
|----------------------------------------------------------------|
|  8-15: Exception <Exception>k__BackingField (8 bytes)          | …
```
=> Shrink SubmissionResponse

test/Exceptionless.Tests/Storage/PersistedDictionaryTests.cs, test/Exceptionless.Tests/Utility/CountDownLatch.cs
=> Use ManualResetEventSlim for waithandle in tests (+increase timeout)

src/Exceptionless/Submission/DefaultSubmissionClient.cs, src/Exceptionless/Submission/SettingsResponse.cs, src/Exceptionless/Submission/SubmissionResponse.cs
* Don't allocate a response for the common paths e.g. `SubmissionResponse == Ok 200`
* Use interpolated strings in preference as that will have a non-boxing; low allocating path in C#10 https://github.com/dotnet/runtime/issues/50635
=> Reduce DefaultSubmissionClient allocations

README.md
Updated from exceptionless.io to exceptionless.com - it seems to hit the incorrect URL
=> Updated readme to point to exceptionless.com

src/Exceptionless/Demystifier/ExceptionExtensions.cs, src/Exceptionless/Extensions/StringExtensions.cs
This helps reduce external code dependencies
=> Internalize client extension methods

src/Exceptionless/Extensions/DataDictionaryExtensions.cs, src/Exceptionless/Serializer/DefaultJsonSerializer.cs, src/Exceptionless/Serializer/JsonTextWriterWithExclusions.cs
Gets called a lot with empty sets so can skip that and the `HashSet` creation and use `string[]` directly
=> Skip pattern maching for empty sets

src/Exceptionless/Models/Client/Data/EnvironmentInfo.cs, src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs, src/Platforms/Exceptionless.Windows/ExceptionlessWindowsEnvironmentInfoCollector.cs, src/Platforms/Exceptionless.Windows/ExceptionlessWindowsExtensions.cs
=> Add ExceptionlessWindowsEnvironmentInfoCollector

test/Exceptionless.Tests/Storage/PersistedDictionaryTests.cs, test/Exceptionless.Tests/Utility/CountDownLatch.cs
fixes #275
An excessive value for the wait timeout on the second call should not matter, but will help if there is some sort of issue in saving which blows out the time. This value can be reduced if the point of the test is to make sure the save happens in a timely manner.
=> bump timeout higher, value shouldn't matter unless latch isn't triggered

src/Exceptionless/Demystifier/EnhancedStackFrame.cs, src/Exceptionless/Demystifier/EnhancedStackTrace.Frames.cs, src/Exceptionless/Demystifier/EnhancedStackTrace.cs, src/Exceptionless/Demystifier/Enumerable/EnumerableIList.cs, src/Exceptionless/Demystifier/Enumerable/EnumeratorIList.cs, src/Exceptionless/Demystifier/Enumerable/IEnumerableIList.cs, src/Exceptionless/Demystifier/Internal/ReflectionHelper.cs, src/Exceptionless/Demystifier/ResolvedMethod.cs, src/Exceptionless/Demystifier/ResolvedParameter.cs, src/Exceptionless/Demystifier/StringBuilderExtentions.cs, src/Exceptionless/Demystifier/TypeNameHelper.cs, src/Exceptionless/Demystifier/ValueTupleResolvedParameter.cs
Resolves #281 by making all of the classes from Ben.Demystifier internal instead of public.
=> Make all Demystifier classes internal

src/Platforms/Exceptionless.Wpf/Exceptionless.Wpf.csproj, src/Platforms/Exceptionless.Wpf/ExceptionlessWpfExtensions.cs
Fixes #290 by add source link to `ExceptionslessWindowsEnvironmentInfoCollector` in the WPF platform project and registering that services to the dependency resolver.
You should only need to use the Wpf client, code is shared between the clients. I'm trying to think if there is any reason we shouldn't be capturing that environment info in wpf. I can't think of any reason not to.. Would you mind submitting a pr to add a source link to that file in the wpf project and then adding a line to `client.Configuration.Resolver.Register<IEnvironmentInfoCollector, ExceptionlessWindowsEnvironmentInfoCollector>();` in register.
_Originally posted by @niemyjski in https://github.com/exceptionless/Exceptionless.Net/issues/290#issuecomment-1398800297_
=> Add Windows environment info collector to the WPF platform

src/Exceptionless/Extensions/ExceptionlessConfigurationExtensions.cs
I noticed you couldn't remove UserIdentity easily.
=> Added ability to remove User Identity

src/Platforms/Exceptionless.NLog/ExceptionlessClientExtensions.cs, src/Platforms/Exceptionless.NLog/ExceptionlessTarget.cs, src/Platforms/Exceptionless.NLog/LogEventBuilderExtensions.cs, src/Platforms/Exceptionless.NLog/NLogExceptionlessLog.cs, src/Platforms/Exceptionless.NLog/readme.txt
Resolves #297 and resolves #296
```xml
    <target type="Exceptionless, Exceptionless.NLog" name="exceptionless"
apiKey="API_KEY_HERE"
userIdentity="${aspnet-user-identity}"
userIdentityName="${aspnet-user-claim:ClaimTypes.Name}">
      <field name="host" layout="${hostname}" />
      <field name="process" layout="${processname}" />
      <field name="user" layout="${environment-user}" />
    </target>
```
[${aspnet-user-identity}](https://github.com/NLog/NLog/wiki/AspNetUserIdentity-layout-renderer) comes from [NLog.Web.AspNetCore](https://www.nuget.org/packages/NLog.Web.AspNetCore)-nuget-package . See also: https://nlog-project.org/config/?tab=layout-renderers
=> ExceptionlessTarget - ApiKey and ServerUrl and Message and UserIdentity with Layout support

src/Platforms/Exceptionless.NLog/ExceptionlessTarget.cs, src/Platforms/Exceptionless.NLog/NLogInternalLoggger.cs
Better user-experience when using NLog, and [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) is the recommended place when troubleshooting.
=> ExceptionlessTarget - ProcessQueueAsync for ExceptionlessClient on Flush

src/Exceptionless/Configuration/ExceptionlessConfiguration.cs, src/Exceptionless/Models/Client/Data/RequestInfo.cs, src/Platforms/Exceptionless.AspNetCore/RequestInfoCollector.cs, src/Platforms/Exceptionless.Web/RequestInfoCollector.cs, src/Platforms/Exceptionless.WebApi/RequestInfoCollector.cs
Before merging this we probably need to make these changes server side as well. 
I also want to add MAX_DATA_ITEM_LENGTH to the other two implementations.
=> Fixes #127: Added ability to record http headers

src/Platforms/Exceptionless.NLog/ExceptionlessTarget.cs
See also: https://github.com/exceptionless/Exceptionless.Net/issues/260
=> NLog ExceptionlessTarget SetDefaultMinLogLevel

src/Exceptionless/Extensions/StringExtensions.cs, src/Exceptionless/Models/Client/ClientConfiguration.cs, src/Exceptionless/Models/Client/Data/EnvironmentInfo.cs, src/Exceptionless/Models/Client/Data/Error.cs, src/Exceptionless/Models/Client/Data/InnerError.cs, src/Exceptionless/Models/Client/Data/ManualStackingInfo.cs, src/Exceptionless/Models/Client/Data/Method.cs, src/Exceptionless/Models/Client/Data/Module.cs, src/Exceptionless/Models/Client/Data/Parameter.cs, src/Exceptionless/Models/Client/Data/RequestInfo.cs, src/Exceptionless/Models/Client/Data/SimpleError.cs, src/Exceptionless/Models/Client/Data/SimpleInnerError.cs, src/Exceptionless/Models/Client/Data/StackFrame.cs, src/Exceptionless/Models/Client/Data/UserDescription.cs, src/Exceptionless/Models/Client/Data/UserInfo.cs, src/Exceptionless/Models/Client/Event.cs, src/Exceptionless/Serializer/DataDictionaryConverter.cs, src/Exceptionless/Serializer/DefaultJsonSerializer.cs, src/Exceptionless/Serializer/ExceptionlessContractResolver.cs, src/Exceptionless/Serializer/JsonTextWriterWithExclusions.cs, test/Exceptionless.Tests/Configuration/DataExclusionTests.cs, test/Exceptionless.Tests/Serializer/JsonSerializerTests.cs, test/Exceptionless.Tests/Serializer/JsonStorageSerializerTests.cs
Breaking change that fixes many serialization issues.
=> Closes #294: Preserving custom object property names sent to SetProperty and AddObject

src/Exceptionless/Extensions/StringExtensions.cs, src/Exceptionless/Logging/FileExceptionlessLog.cs, src/Exceptionless/Logging/IsolatedStorageFileExceptionlessLog.cs, test/Exceptionless.Tests/Storage/FileStorageTestsBase.cs
Addresses https://github.com/exceptionless/Exceptionless.Net/pull/257
=> Lock conflicts occur when multiple sites (with ExceptionLess.net) are deployed on a server

src/Exceptionless/Configuration/SettingsManager.cs, src/Exceptionless/ExceptionlessClient.cs, src/Exceptionless/Extensions/ExceptionlessClientExtensions.cs, src/Exceptionless/Submission/DefaultSubmissionClient.cs
Found a case where process exit and unhandled event handlers will return early due to being marked async causing early exit. This could potentially (unlikely) cause a dead lock on shutdown due to GetAwaiter().GetResult() but benefits greatly outweigh (I was also unable to cause this scenario with a deadlock)
Also, we may want to consider having our internal trace loggers implement disposable so flush is called (may be happing today by ioc but flush and dispose is not called by default)
I also greatly improved logging of the client to give more visibility of what is happening instead of only logging on error:
```
2023-05-09 08:01:44.3824 Info  ExceptionlessClient: Startup called ApiKey=MY_API_KEY ServerUrl=https://localhost:5000
2023-05-09 08:01:44.5095 Info  ExceptionlessClient: Startup …
```
=> Fixed issues with async event handlers and improved trace logging

src/Exceptionless/Extensions/ExceptionlessClientExtensions.cs, src/Platforms/Exceptionless.Web/ExceptionlessClientExtensions.cs, src/Platforms/Exceptionless.Windows/ExceptionlessClientExtensions.cs, src/Platforms/Exceptionless.Wpf/ExceptionlessClientExtensions.cs
Also improved logging
```
2023-05-18 07:35:46.3627 Info  ExceptionlessClient: Startup finished
2023-05-18 07:35:51.7581 Info  ExceptionlessClient: Application.Current.DispatcherUnhandledException called
2023-05-18 07:35:57.5818 Info  ExceptionlessClient: Processing event queue
2023-05-18 07:35:57.8918 Info  DefaultEventQueue: Sent 1 events to "http://localhost".
2023-05-18 07:35:57.8927 Info  ExceptionlessClient: Application.Current.DispatcherUnhandledException finished
2023-05-18 07:35:58.8683 Info  ExceptionlessClient: AppDomain.CurrentDomain.UnhandledException called
2023-05-18 07:35:58.8703 Info  ErrorPlugin: Event submission cancelled by plugin: refid= type=error message=
2023-05-18 07:35:58.8704 Info  ExceptionlessClient: Event submission cancelled by event pipeline: refid= …
```
=> Fixed a bug where Application.ThreadException, HttpApplication.Error, Application.Current.DispatcherUnhandledException may not be logged

src/Exceptionless/Exceptionless.csproj, src/Exceptionless/Extensions/ExceptionlessConfigurationExtensions.cs, src/Platforms/Exceptionless.Extensions.Hosting/ExceptionlessExtensions.cs
This allows for other consumers using .NET Core clients like WPF to use IConfiguration.
```
ExceptionlessClient.Default.Configuration.ReadFromConfiguration(config);
ExceptionlessClient.Default.Register();
```
We are taking a dep on the LTS abstraction, it would be great to automatically read from configuration but:
1. We would have to take out much larger dependencies..
2. We wouldn't know your naming scheme of your configuration files...
=> Add support for IConfiguration when using netstandard.

src/Exceptionless/Exceptionless.csproj, src/Exceptionless/Plugins/Default/080_VersionPlugin.cs, src/Exceptionless/Services/DefaultEnvironmentInfoCollector.cs, src/Exceptionless/Utility/AssemblyHelper.cs
This removes .NET Platform 1.0 and 1.1 only supported apis from the core netstandard client.
- https://github.com/aspnet/Announcements/issues/237
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.platformabstractions.platformservices.default?view=dotnet-plat-ext-1.1
- https://stackoverflow.com/questions/46226283/netstandard-2-0-does-not-have-appdomain-currentdomain-setupinformation-configura
- http://www.hishambinateya.com/goodbye-platform-abstractions
- https://github.com/aspnet/PlatformAbstractions/issues/50
There is a slight change in behavior as I'm trying to reuse some existing logic to smartly detect the entry assembly and exclude Exceptionless and Microsoft Packages (We could use this in a few more spots but wanted to keep this minimal). Here is the diff before …
=> Remove Deprecated Microsoft.Extensions.PlatformAbstractions
